// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Data;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825090611_RemoveNavigationFromMunicipalityToElection")]
    partial class RemoveNavigationFromMunicipalityToElection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartyGroupPoliticalParty", b =>
                {
                    b.Property<int>("PartyGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartiesId")
                        .HasColumnType("int");

                    b.HasKey("PartyGroupsId", "PoliticalPartiesId");

                    b.HasIndex("PoliticalPartiesId");

                    b.ToTable("PartyGroupPoliticalParty");
                });

            modelBuilder.Entity("PartyGroupScenario", b =>
                {
                    b.Property<int>("PartyGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("ScenariosId")
                        .HasColumnType("int");

                    b.HasKey("PartyGroupsId", "ScenariosId");

                    b.HasIndex("ScenariosId");

                    b.ToTable("PartyGroupScenario");
                });

            modelBuilder.Entity("Repositories.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionYear")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionYear")
                        .IsUnique();

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionConstituency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("FixedSeatCount")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("Name", "ElectionId", "MunicipalityId")
                        .IsUnique();

                    b.ToTable("ElectionConstituencies");
                });

            modelBuilder.Entity("Repositories.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ElectionAreaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MunicipalityCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityCode", "ElectionAreaName")
                        .IsUnique();

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("Repositories.Entities.OriginalConstituencyVoteResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionConstituencyId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVotes")
                        .HasColumnType("int");

                    b.Property<int>("OriginalElectionResultSetId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionConstituencyId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("OriginalElectionResultSetId", "ElectionConstituencyId", "PoliticalPartyId")
                        .IsUnique();

                    b.ToTable("OriginalConstituencyVoteResults");
                });

            modelBuilder.Entity("Repositories.Entities.OriginalCouncilSeatAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocatedSeat")
                        .HasColumnType("int");

                    b.Property<decimal>("AllocationDivisor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ComparisonNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OriginalElectionResultSetId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeatCountForPartyBeforeAllocation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OriginalElectionResultSetId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("AllocatedSeat", "PoliticalPartyId", "OriginalElectionResultSetId")
                        .IsUnique();

                    b.ToTable("OriginalCouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.OriginalElectionResultSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCouncilSeatCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("UserId", "MunicipalityId", "ElectionId")
                        .IsUnique();

                    b.ToTable("OriginalElectionResultSets");
                });

            modelBuilder.Entity("Repositories.Entities.PartyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("PartyGroups");
                });

            modelBuilder.Entity("Repositories.Entities.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsParliamentary")
                        .HasColumnType("bit");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "MunicipalityId")
                        .IsUnique()
                        .HasFilter("[MunicipalityId] IS NOT NULL");

                    b.ToTable("PoliticalParties");
                });

            modelBuilder.Entity("Repositories.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Repositories.Entities.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OriginalElectionResultSetId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OriginalElectionResultSetId");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId")
                        .IsUnique();

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("Repositories.Entities.ScenarioConstituencyVoteResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectionConstituencyId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVotes")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionConstituencyId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("PoliticalPartyId", "ScenarioId")
                        .IsUnique();

                    b.ToTable("ScenarioConstituencyVoteResults");
                });

            modelBuilder.Entity("Repositories.Entities.ScenarioCouncilSeatAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocatedSeat")
                        .HasColumnType("int");

                    b.Property<decimal>("AllocationDivisor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ComparisonNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeatCountForPartyBeforeAllocation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("AllocatedSeat", "ScenarioId", "PoliticalPartyId")
                        .IsUnique();

                    b.ToTable("ScenarioCouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("FailedLogIns")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PartyGroupPoliticalParty", b =>
                {
                    b.HasOne("Repositories.Entities.PartyGroup", null)
                        .WithMany()
                        .HasForeignKey("PartyGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", null)
                        .WithMany()
                        .HasForeignKey("PoliticalPartiesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGroupScenario", b =>
                {
                    b.HasOne("Repositories.Entities.PartyGroup", null)
                        .WithMany()
                        .HasForeignKey("PartyGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Scenario", null)
                        .WithMany()
                        .HasForeignKey("ScenariosId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Entities.ElectionConstituency", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("ElectionConstituencies")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("ElectionConstituencies")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Repositories.Entities.OriginalConstituencyVoteResult", b =>
                {
                    b.HasOne("Repositories.Entities.ElectionConstituency", "ElectionConstituency")
                        .WithMany("OriginalConstituencyVoteResults")
                        .HasForeignKey("ElectionConstituencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.OriginalElectionResultSet", "OriginalElectionResultSet")
                        .WithMany("OriginalConstituencyVoteResults")
                        .HasForeignKey("OriginalElectionResultSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("OriginalConstituencyVoteResults")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ElectionConstituency");

                    b.Navigation("OriginalElectionResultSet");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Repositories.Entities.OriginalCouncilSeatAllocation", b =>
                {
                    b.HasOne("Repositories.Entities.OriginalElectionResultSet", "OriginalElectionResultSet")
                        .WithMany("OriginalCouncilSeatAllocations")
                        .HasForeignKey("OriginalElectionResultSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("OriginalCouncilSeatAllocations")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalElectionResultSet");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Repositories.Entities.OriginalElectionResultSet", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("OriginalElectionResultSets")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("OriginalElectionResultSets")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.User", "User")
                        .WithMany("OriginalElectionResultSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Municipality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.PartyGroup", b =>
                {
                    b.HasOne("Repositories.Entities.User", "User")
                        .WithMany("PartyGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.PoliticalParty", b =>
                {
                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("PoliticalParties")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repositories.Entities.User", "User")
                        .WithMany("PoliticalParties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Municipality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.RefreshToken", b =>
                {
                    b.HasOne("Repositories.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.Scenario", b =>
                {
                    b.HasOne("Repositories.Entities.OriginalElectionResultSet", "OriginalElectionResultSet")
                        .WithMany("Scenarios")
                        .HasForeignKey("OriginalElectionResultSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.User", "User")
                        .WithMany("Scenarios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalElectionResultSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.ScenarioConstituencyVoteResult", b =>
                {
                    b.HasOne("Repositories.Entities.ElectionConstituency", "ElectionConstituency")
                        .WithMany("ScenarioConstituencyVoteResults")
                        .HasForeignKey("ElectionConstituencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("ScenarioConstituencyVoteResults")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Scenario", "Scenario")
                        .WithMany("ScenarioConstituencyVoteResults")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectionConstituency");

                    b.Navigation("PoliticalParty");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Repositories.Entities.ScenarioCouncilSeatAllocation", b =>
                {
                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("ScenarioCouncilSeatAllocations")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Scenario", "Scenario")
                        .WithMany("ScenarioCouncilSeatAllocations")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliticalParty");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("Repositories.Entities.Election", b =>
                {
                    b.Navigation("ElectionConstituencies");

                    b.Navigation("OriginalElectionResultSets");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionConstituency", b =>
                {
                    b.Navigation("OriginalConstituencyVoteResults");

                    b.Navigation("ScenarioConstituencyVoteResults");
                });

            modelBuilder.Entity("Repositories.Entities.Municipality", b =>
                {
                    b.Navigation("ElectionConstituencies");

                    b.Navigation("OriginalElectionResultSets");

                    b.Navigation("PoliticalParties");
                });

            modelBuilder.Entity("Repositories.Entities.OriginalElectionResultSet", b =>
                {
                    b.Navigation("OriginalConstituencyVoteResults");

                    b.Navigation("OriginalCouncilSeatAllocations");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("Repositories.Entities.PoliticalParty", b =>
                {
                    b.Navigation("OriginalConstituencyVoteResults");

                    b.Navigation("OriginalCouncilSeatAllocations");

                    b.Navigation("ScenarioConstituencyVoteResults");

                    b.Navigation("ScenarioCouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.Scenario", b =>
                {
                    b.Navigation("ScenarioConstituencyVoteResults");

                    b.Navigation("ScenarioCouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.User", b =>
                {
                    b.Navigation("OriginalElectionResultSets");

                    b.Navigation("PartyGroups");

                    b.Navigation("PoliticalParties");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Scenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
