// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Data;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725191648_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MunicipalityPoliticalParty", b =>
                {
                    b.Property<int>("MunicipalitiesId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartiesId")
                        .HasColumnType("int");

                    b.HasKey("MunicipalitiesId", "PoliticalPartiesId");

                    b.HasIndex("PoliticalPartiesId");

                    b.ToTable("MunicipalityPoliticalParty", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocationDivisor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ComparisonNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionResultId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("PartySeatCountBeforeAllocation")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectionResultId");

                    b.HasIndex("MunicipalityId", "ElectionId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("CouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocationScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocationDivisor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ComparisonNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("PartySeatCountBeforeAllocation")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VoteCountUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("UserId");

                    b.HasIndex("MunicipalityId", "ElectionId", "SeatNumber", "UserId")
                        .IsUnique();

                    b.ToTable("CouncilSeatAllocationsScenarios");
                });

            modelBuilder.Entity("Repositories.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ElectionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ElectionDate")
                        .IsUnique();

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVotes")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<decimal>("VotePercentage")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("MunicipalityId", "PoliticalPartyId", "ElectionId")
                        .IsUnique();

                    b.ToTable("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CouncilSeatCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("Repositories.Entities.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocal")
                        .HasColumnType("bit");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PartyName")
                        .IsUnique();

                    b.ToTable("PoliticalParties");
                });

            modelBuilder.Entity("Repositories.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("FailedLogIns")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MunicipalityPoliticalParty", b =>
                {
                    b.HasOne("Repositories.Entities.Municipality", null)
                        .WithMany()
                        .HasForeignKey("MunicipalitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", null)
                        .WithMany()
                        .HasForeignKey("PoliticalPartiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocation", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("CouncilSeatAllocations")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.ElectionResult", "ElectionResult")
                        .WithMany("CouncilSeatAllocations")
                        .HasForeignKey("ElectionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("CouncilSeatAllocations")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("ElectionResult");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocationScenario", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.User", "User")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Municipality");

                    b.Navigation("PoliticalParty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionResult", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("ElectionResults")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("ElectionResults")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("ElectionResults")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Municipality");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Repositories.Entities.Election", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");

                    b.Navigation("CouncilSeatAllocations");

                    b.Navigation("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionResult", b =>
                {
                    b.Navigation("CouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.Municipality", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");

                    b.Navigation("CouncilSeatAllocations");

                    b.Navigation("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.PoliticalParty", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");

                    b.Navigation("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.User", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
