// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Data;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726153035_AddDataToTablePoliticalParties")]
    partial class AddDataToTablePoliticalParties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MunicipalityPoliticalParty", b =>
                {
                    b.Property<int>("MunicipalitiesId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartiesId")
                        .HasColumnType("int");

                    b.HasKey("MunicipalitiesId", "PoliticalPartiesId");

                    b.HasIndex("PoliticalPartiesId");

                    b.ToTable("MunicipalityPoliticalParty", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocationDivisor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ComparisonNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionResultId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("PartySeatCountBeforeAllocation")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectionResultId");

                    b.HasIndex("MunicipalityId", "ElectionId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("CouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocationScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocationDivisor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ComparisonNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("PartySeatCountBeforeAllocation")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VoteCountUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("UserId");

                    b.HasIndex("MunicipalityId", "ElectionId", "SeatNumber", "UserId")
                        .IsUnique();

                    b.ToTable("CouncilSeatAllocationsScenarios");
                });

            modelBuilder.Entity("Repositories.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ElectionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ElectionDate")
                        .IsUnique();

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVotes")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<decimal>("VotePercentage")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("MunicipalityId", "PoliticalPartyId", "ElectionId")
                        .IsUnique();

                    b.ToTable("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CouncilSeatCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouncilSeatCount = 0,
                            Name = "Ale"
                        },
                        new
                        {
                            Id = 2,
                            CouncilSeatCount = 0,
                            Name = "Alingsås"
                        },
                        new
                        {
                            Id = 3,
                            CouncilSeatCount = 0,
                            Name = "Alvesta"
                        },
                        new
                        {
                            Id = 4,
                            CouncilSeatCount = 0,
                            Name = "Aneby"
                        },
                        new
                        {
                            Id = 5,
                            CouncilSeatCount = 0,
                            Name = "Arboga"
                        },
                        new
                        {
                            Id = 6,
                            CouncilSeatCount = 0,
                            Name = "Arjeplog"
                        },
                        new
                        {
                            Id = 7,
                            CouncilSeatCount = 0,
                            Name = "Arvidsjaur"
                        },
                        new
                        {
                            Id = 8,
                            CouncilSeatCount = 0,
                            Name = "Arvika"
                        },
                        new
                        {
                            Id = 9,
                            CouncilSeatCount = 0,
                            Name = "Askersund"
                        },
                        new
                        {
                            Id = 10,
                            CouncilSeatCount = 0,
                            Name = "Avesta"
                        },
                        new
                        {
                            Id = 11,
                            CouncilSeatCount = 0,
                            Name = "Bengtsfors"
                        },
                        new
                        {
                            Id = 12,
                            CouncilSeatCount = 0,
                            Name = "Berg"
                        },
                        new
                        {
                            Id = 13,
                            CouncilSeatCount = 0,
                            Name = "Bjurholm"
                        },
                        new
                        {
                            Id = 14,
                            CouncilSeatCount = 0,
                            Name = "Bjuv"
                        },
                        new
                        {
                            Id = 15,
                            CouncilSeatCount = 0,
                            Name = "Boden"
                        },
                        new
                        {
                            Id = 16,
                            CouncilSeatCount = 0,
                            Name = "Bollebygd"
                        },
                        new
                        {
                            Id = 17,
                            CouncilSeatCount = 0,
                            Name = "Bollnäs"
                        },
                        new
                        {
                            Id = 18,
                            CouncilSeatCount = 0,
                            Name = "Borgholm"
                        },
                        new
                        {
                            Id = 19,
                            CouncilSeatCount = 0,
                            Name = "Borlänge"
                        },
                        new
                        {
                            Id = 20,
                            CouncilSeatCount = 0,
                            Name = "Borås"
                        },
                        new
                        {
                            Id = 21,
                            CouncilSeatCount = 0,
                            Name = "Botkyrka"
                        },
                        new
                        {
                            Id = 22,
                            CouncilSeatCount = 0,
                            Name = "Boxholm"
                        },
                        new
                        {
                            Id = 23,
                            CouncilSeatCount = 0,
                            Name = "Bromölla"
                        },
                        new
                        {
                            Id = 24,
                            CouncilSeatCount = 0,
                            Name = "Bräcke"
                        },
                        new
                        {
                            Id = 25,
                            CouncilSeatCount = 0,
                            Name = "Burlöv"
                        },
                        new
                        {
                            Id = 26,
                            CouncilSeatCount = 0,
                            Name = "Båstad"
                        },
                        new
                        {
                            Id = 27,
                            CouncilSeatCount = 0,
                            Name = "Dals-Ed"
                        },
                        new
                        {
                            Id = 28,
                            CouncilSeatCount = 0,
                            Name = "Danderyd"
                        },
                        new
                        {
                            Id = 29,
                            CouncilSeatCount = 0,
                            Name = "Degerfors"
                        },
                        new
                        {
                            Id = 30,
                            CouncilSeatCount = 0,
                            Name = "Dorotea"
                        },
                        new
                        {
                            Id = 31,
                            CouncilSeatCount = 0,
                            Name = "Eda"
                        },
                        new
                        {
                            Id = 32,
                            CouncilSeatCount = 0,
                            Name = "Ekerö"
                        },
                        new
                        {
                            Id = 33,
                            CouncilSeatCount = 0,
                            Name = "Eksjö"
                        },
                        new
                        {
                            Id = 34,
                            CouncilSeatCount = 0,
                            Name = "Emmaboda"
                        },
                        new
                        {
                            Id = 35,
                            CouncilSeatCount = 0,
                            Name = "Enköping"
                        },
                        new
                        {
                            Id = 36,
                            CouncilSeatCount = 0,
                            Name = "Eskilstuna"
                        },
                        new
                        {
                            Id = 37,
                            CouncilSeatCount = 0,
                            Name = "Eslöv"
                        },
                        new
                        {
                            Id = 38,
                            CouncilSeatCount = 0,
                            Name = "Essunga"
                        },
                        new
                        {
                            Id = 39,
                            CouncilSeatCount = 0,
                            Name = "Fagersta"
                        },
                        new
                        {
                            Id = 40,
                            CouncilSeatCount = 0,
                            Name = "Falun"
                        },
                        new
                        {
                            Id = 41,
                            CouncilSeatCount = 0,
                            Name = "Filipstad"
                        },
                        new
                        {
                            Id = 42,
                            CouncilSeatCount = 0,
                            Name = "Finspång"
                        },
                        new
                        {
                            Id = 43,
                            CouncilSeatCount = 0,
                            Name = "Flen"
                        },
                        new
                        {
                            Id = 44,
                            CouncilSeatCount = 0,
                            Name = "Forshaga"
                        },
                        new
                        {
                            Id = 45,
                            CouncilSeatCount = 0,
                            Name = "Gagnef"
                        },
                        new
                        {
                            Id = 46,
                            CouncilSeatCount = 0,
                            Name = "Gislaved"
                        },
                        new
                        {
                            Id = 47,
                            CouncilSeatCount = 0,
                            Name = "Gnesta"
                        },
                        new
                        {
                            Id = 48,
                            CouncilSeatCount = 0,
                            Name = "Gnosjö"
                        },
                        new
                        {
                            Id = 49,
                            CouncilSeatCount = 0,
                            Name = "Gotland"
                        },
                        new
                        {
                            Id = 50,
                            CouncilSeatCount = 0,
                            Name = "Grums"
                        },
                        new
                        {
                            Id = 51,
                            CouncilSeatCount = 0,
                            Name = "Grästorp"
                        },
                        new
                        {
                            Id = 52,
                            CouncilSeatCount = 0,
                            Name = "Gullspång"
                        },
                        new
                        {
                            Id = 53,
                            CouncilSeatCount = 0,
                            Name = "Gällivare"
                        },
                        new
                        {
                            Id = 54,
                            CouncilSeatCount = 0,
                            Name = "Gävle"
                        },
                        new
                        {
                            Id = 55,
                            CouncilSeatCount = 0,
                            Name = "Göteborg"
                        },
                        new
                        {
                            Id = 56,
                            CouncilSeatCount = 0,
                            Name = "Götene"
                        },
                        new
                        {
                            Id = 57,
                            CouncilSeatCount = 0,
                            Name = "Habo"
                        },
                        new
                        {
                            Id = 58,
                            CouncilSeatCount = 0,
                            Name = "Hagfors"
                        },
                        new
                        {
                            Id = 59,
                            CouncilSeatCount = 0,
                            Name = "Hallsberg"
                        },
                        new
                        {
                            Id = 60,
                            CouncilSeatCount = 0,
                            Name = "Hallstahammar"
                        },
                        new
                        {
                            Id = 61,
                            CouncilSeatCount = 0,
                            Name = "Halmstad"
                        },
                        new
                        {
                            Id = 62,
                            CouncilSeatCount = 0,
                            Name = "Hammarö"
                        },
                        new
                        {
                            Id = 63,
                            CouncilSeatCount = 0,
                            Name = "Haninge"
                        },
                        new
                        {
                            Id = 64,
                            CouncilSeatCount = 0,
                            Name = "Haparanda"
                        },
                        new
                        {
                            Id = 65,
                            CouncilSeatCount = 0,
                            Name = "Heby"
                        },
                        new
                        {
                            Id = 66,
                            CouncilSeatCount = 0,
                            Name = "Hedemora"
                        },
                        new
                        {
                            Id = 67,
                            CouncilSeatCount = 0,
                            Name = "Helsingborg"
                        },
                        new
                        {
                            Id = 68,
                            CouncilSeatCount = 0,
                            Name = "Herrljunga"
                        },
                        new
                        {
                            Id = 69,
                            CouncilSeatCount = 0,
                            Name = "Hjo"
                        },
                        new
                        {
                            Id = 70,
                            CouncilSeatCount = 0,
                            Name = "Hofors"
                        },
                        new
                        {
                            Id = 71,
                            CouncilSeatCount = 0,
                            Name = "Huddinge"
                        },
                        new
                        {
                            Id = 72,
                            CouncilSeatCount = 0,
                            Name = "Hudiksvall"
                        },
                        new
                        {
                            Id = 73,
                            CouncilSeatCount = 0,
                            Name = "Hultsfred"
                        },
                        new
                        {
                            Id = 74,
                            CouncilSeatCount = 0,
                            Name = "Hylte"
                        },
                        new
                        {
                            Id = 75,
                            CouncilSeatCount = 0,
                            Name = "Håbo"
                        },
                        new
                        {
                            Id = 76,
                            CouncilSeatCount = 0,
                            Name = "Hällefors"
                        },
                        new
                        {
                            Id = 77,
                            CouncilSeatCount = 0,
                            Name = "Härjedalen"
                        },
                        new
                        {
                            Id = 78,
                            CouncilSeatCount = 0,
                            Name = "Härnösand"
                        },
                        new
                        {
                            Id = 79,
                            CouncilSeatCount = 0,
                            Name = "Härryda"
                        },
                        new
                        {
                            Id = 80,
                            CouncilSeatCount = 0,
                            Name = "Hässleholm"
                        },
                        new
                        {
                            Id = 81,
                            CouncilSeatCount = 0,
                            Name = "Höganäs"
                        },
                        new
                        {
                            Id = 82,
                            CouncilSeatCount = 0,
                            Name = "Högsby"
                        },
                        new
                        {
                            Id = 83,
                            CouncilSeatCount = 0,
                            Name = "Hörby"
                        },
                        new
                        {
                            Id = 84,
                            CouncilSeatCount = 0,
                            Name = "Höör"
                        },
                        new
                        {
                            Id = 85,
                            CouncilSeatCount = 0,
                            Name = "Jokkmokk"
                        },
                        new
                        {
                            Id = 86,
                            CouncilSeatCount = 0,
                            Name = "Järfälla"
                        },
                        new
                        {
                            Id = 87,
                            CouncilSeatCount = 0,
                            Name = "Jönköping"
                        },
                        new
                        {
                            Id = 88,
                            CouncilSeatCount = 0,
                            Name = "Kalix"
                        },
                        new
                        {
                            Id = 89,
                            CouncilSeatCount = 0,
                            Name = "Kalmar"
                        },
                        new
                        {
                            Id = 90,
                            CouncilSeatCount = 0,
                            Name = "Karlsborg"
                        },
                        new
                        {
                            Id = 91,
                            CouncilSeatCount = 0,
                            Name = "Karlshamn"
                        },
                        new
                        {
                            Id = 92,
                            CouncilSeatCount = 0,
                            Name = "Karlskoga"
                        },
                        new
                        {
                            Id = 93,
                            CouncilSeatCount = 0,
                            Name = "Karlskrona"
                        },
                        new
                        {
                            Id = 94,
                            CouncilSeatCount = 0,
                            Name = "Karlstad"
                        },
                        new
                        {
                            Id = 95,
                            CouncilSeatCount = 0,
                            Name = "Katrineholm"
                        },
                        new
                        {
                            Id = 96,
                            CouncilSeatCount = 0,
                            Name = "Kil"
                        },
                        new
                        {
                            Id = 97,
                            CouncilSeatCount = 0,
                            Name = "Kinda"
                        },
                        new
                        {
                            Id = 98,
                            CouncilSeatCount = 0,
                            Name = "Kiruna"
                        },
                        new
                        {
                            Id = 99,
                            CouncilSeatCount = 0,
                            Name = "Klippan"
                        },
                        new
                        {
                            Id = 100,
                            CouncilSeatCount = 0,
                            Name = "Knivsta"
                        },
                        new
                        {
                            Id = 101,
                            CouncilSeatCount = 0,
                            Name = "Kramfors"
                        },
                        new
                        {
                            Id = 102,
                            CouncilSeatCount = 0,
                            Name = "Kristianstad"
                        },
                        new
                        {
                            Id = 103,
                            CouncilSeatCount = 0,
                            Name = "Kristinehamn"
                        },
                        new
                        {
                            Id = 104,
                            CouncilSeatCount = 0,
                            Name = "Krokom"
                        },
                        new
                        {
                            Id = 105,
                            CouncilSeatCount = 0,
                            Name = "Kumla"
                        },
                        new
                        {
                            Id = 106,
                            CouncilSeatCount = 0,
                            Name = "Kungsbacka"
                        },
                        new
                        {
                            Id = 107,
                            CouncilSeatCount = 0,
                            Name = "Kungsör"
                        },
                        new
                        {
                            Id = 108,
                            CouncilSeatCount = 0,
                            Name = "Kungälv"
                        },
                        new
                        {
                            Id = 109,
                            CouncilSeatCount = 0,
                            Name = "Kävlinge"
                        },
                        new
                        {
                            Id = 110,
                            CouncilSeatCount = 0,
                            Name = "Köping"
                        },
                        new
                        {
                            Id = 111,
                            CouncilSeatCount = 0,
                            Name = "Laholm"
                        },
                        new
                        {
                            Id = 112,
                            CouncilSeatCount = 0,
                            Name = "Landskrona"
                        },
                        new
                        {
                            Id = 113,
                            CouncilSeatCount = 0,
                            Name = "Laxå"
                        },
                        new
                        {
                            Id = 114,
                            CouncilSeatCount = 0,
                            Name = "Lekeberg"
                        },
                        new
                        {
                            Id = 115,
                            CouncilSeatCount = 0,
                            Name = "Leksand"
                        },
                        new
                        {
                            Id = 116,
                            CouncilSeatCount = 0,
                            Name = "Lerum"
                        },
                        new
                        {
                            Id = 117,
                            CouncilSeatCount = 0,
                            Name = "Lessebo"
                        },
                        new
                        {
                            Id = 118,
                            CouncilSeatCount = 0,
                            Name = "Lidingö"
                        },
                        new
                        {
                            Id = 119,
                            CouncilSeatCount = 0,
                            Name = "Lidköping"
                        },
                        new
                        {
                            Id = 120,
                            CouncilSeatCount = 0,
                            Name = "Lilla Edet"
                        },
                        new
                        {
                            Id = 121,
                            CouncilSeatCount = 0,
                            Name = "Lindesberg"
                        },
                        new
                        {
                            Id = 122,
                            CouncilSeatCount = 0,
                            Name = "Linköping"
                        },
                        new
                        {
                            Id = 123,
                            CouncilSeatCount = 0,
                            Name = "Ljungby"
                        },
                        new
                        {
                            Id = 124,
                            CouncilSeatCount = 0,
                            Name = "Ljusdal"
                        },
                        new
                        {
                            Id = 125,
                            CouncilSeatCount = 0,
                            Name = "Ljusnarsberg"
                        },
                        new
                        {
                            Id = 126,
                            CouncilSeatCount = 0,
                            Name = "Lomma"
                        },
                        new
                        {
                            Id = 127,
                            CouncilSeatCount = 0,
                            Name = "Ludvika"
                        },
                        new
                        {
                            Id = 128,
                            CouncilSeatCount = 0,
                            Name = "Luleå"
                        },
                        new
                        {
                            Id = 129,
                            CouncilSeatCount = 0,
                            Name = "Lund"
                        },
                        new
                        {
                            Id = 130,
                            CouncilSeatCount = 0,
                            Name = "Lycksele"
                        },
                        new
                        {
                            Id = 131,
                            CouncilSeatCount = 0,
                            Name = "Lysekil"
                        },
                        new
                        {
                            Id = 132,
                            CouncilSeatCount = 0,
                            Name = "Malmö"
                        },
                        new
                        {
                            Id = 133,
                            CouncilSeatCount = 0,
                            Name = "Malung-Sälen"
                        },
                        new
                        {
                            Id = 134,
                            CouncilSeatCount = 0,
                            Name = "Malå"
                        },
                        new
                        {
                            Id = 135,
                            CouncilSeatCount = 0,
                            Name = "Mariestad"
                        },
                        new
                        {
                            Id = 136,
                            CouncilSeatCount = 0,
                            Name = "Mark"
                        },
                        new
                        {
                            Id = 137,
                            CouncilSeatCount = 0,
                            Name = "Markaryd"
                        },
                        new
                        {
                            Id = 138,
                            CouncilSeatCount = 0,
                            Name = "Mellerud"
                        },
                        new
                        {
                            Id = 139,
                            CouncilSeatCount = 0,
                            Name = "Mjölby"
                        },
                        new
                        {
                            Id = 140,
                            CouncilSeatCount = 0,
                            Name = "Mora"
                        },
                        new
                        {
                            Id = 141,
                            CouncilSeatCount = 0,
                            Name = "Motala"
                        },
                        new
                        {
                            Id = 142,
                            CouncilSeatCount = 0,
                            Name = "Mullsjö"
                        },
                        new
                        {
                            Id = 143,
                            CouncilSeatCount = 0,
                            Name = "Munkedal"
                        },
                        new
                        {
                            Id = 144,
                            CouncilSeatCount = 0,
                            Name = "Munkfors"
                        },
                        new
                        {
                            Id = 145,
                            CouncilSeatCount = 0,
                            Name = "Mölndal"
                        },
                        new
                        {
                            Id = 146,
                            CouncilSeatCount = 0,
                            Name = "Mönsterås"
                        },
                        new
                        {
                            Id = 147,
                            CouncilSeatCount = 0,
                            Name = "Mörbylånga"
                        },
                        new
                        {
                            Id = 148,
                            CouncilSeatCount = 0,
                            Name = "Nacka"
                        },
                        new
                        {
                            Id = 149,
                            CouncilSeatCount = 0,
                            Name = "Nora"
                        },
                        new
                        {
                            Id = 150,
                            CouncilSeatCount = 0,
                            Name = "Norberg"
                        },
                        new
                        {
                            Id = 151,
                            CouncilSeatCount = 0,
                            Name = "Nordanstig"
                        },
                        new
                        {
                            Id = 152,
                            CouncilSeatCount = 0,
                            Name = "Nordmaling"
                        },
                        new
                        {
                            Id = 153,
                            CouncilSeatCount = 0,
                            Name = "Norrköping"
                        },
                        new
                        {
                            Id = 154,
                            CouncilSeatCount = 0,
                            Name = "Norrtälje"
                        },
                        new
                        {
                            Id = 155,
                            CouncilSeatCount = 0,
                            Name = "Norsjö"
                        },
                        new
                        {
                            Id = 156,
                            CouncilSeatCount = 0,
                            Name = "Nybro"
                        },
                        new
                        {
                            Id = 157,
                            CouncilSeatCount = 0,
                            Name = "Nykvarn"
                        },
                        new
                        {
                            Id = 158,
                            CouncilSeatCount = 0,
                            Name = "Nyköping"
                        },
                        new
                        {
                            Id = 159,
                            CouncilSeatCount = 0,
                            Name = "Nynäshamn"
                        },
                        new
                        {
                            Id = 160,
                            CouncilSeatCount = 0,
                            Name = "Nässjö"
                        },
                        new
                        {
                            Id = 161,
                            CouncilSeatCount = 0,
                            Name = "Ockelbo"
                        },
                        new
                        {
                            Id = 162,
                            CouncilSeatCount = 0,
                            Name = "Olofström"
                        },
                        new
                        {
                            Id = 163,
                            CouncilSeatCount = 0,
                            Name = "Orsa"
                        },
                        new
                        {
                            Id = 164,
                            CouncilSeatCount = 0,
                            Name = "Orust"
                        },
                        new
                        {
                            Id = 165,
                            CouncilSeatCount = 0,
                            Name = "Osby"
                        },
                        new
                        {
                            Id = 166,
                            CouncilSeatCount = 0,
                            Name = "Oskarshamn"
                        },
                        new
                        {
                            Id = 167,
                            CouncilSeatCount = 0,
                            Name = "Ovanåker"
                        },
                        new
                        {
                            Id = 168,
                            CouncilSeatCount = 0,
                            Name = "Oxelösund"
                        },
                        new
                        {
                            Id = 169,
                            CouncilSeatCount = 0,
                            Name = "Pajala"
                        },
                        new
                        {
                            Id = 170,
                            CouncilSeatCount = 0,
                            Name = "Partille"
                        },
                        new
                        {
                            Id = 171,
                            CouncilSeatCount = 0,
                            Name = "Perstorp"
                        },
                        new
                        {
                            Id = 172,
                            CouncilSeatCount = 0,
                            Name = "Piteå"
                        },
                        new
                        {
                            Id = 173,
                            CouncilSeatCount = 0,
                            Name = "Ragunda"
                        },
                        new
                        {
                            Id = 174,
                            CouncilSeatCount = 0,
                            Name = "Robertsfors"
                        },
                        new
                        {
                            Id = 175,
                            CouncilSeatCount = 0,
                            Name = "Ronneby"
                        },
                        new
                        {
                            Id = 176,
                            CouncilSeatCount = 0,
                            Name = "Rättvik"
                        },
                        new
                        {
                            Id = 177,
                            CouncilSeatCount = 0,
                            Name = "Sala"
                        },
                        new
                        {
                            Id = 178,
                            CouncilSeatCount = 0,
                            Name = "Salem"
                        },
                        new
                        {
                            Id = 179,
                            CouncilSeatCount = 0,
                            Name = "Sandviken"
                        },
                        new
                        {
                            Id = 180,
                            CouncilSeatCount = 0,
                            Name = "Sigtuna"
                        },
                        new
                        {
                            Id = 181,
                            CouncilSeatCount = 0,
                            Name = "Simrishamn"
                        },
                        new
                        {
                            Id = 182,
                            CouncilSeatCount = 0,
                            Name = "Sjöbo"
                        },
                        new
                        {
                            Id = 183,
                            CouncilSeatCount = 0,
                            Name = "Skara"
                        },
                        new
                        {
                            Id = 184,
                            CouncilSeatCount = 0,
                            Name = "Skellefteå"
                        },
                        new
                        {
                            Id = 185,
                            CouncilSeatCount = 0,
                            Name = "Skinnskatteberg"
                        },
                        new
                        {
                            Id = 186,
                            CouncilSeatCount = 0,
                            Name = "Skurup"
                        },
                        new
                        {
                            Id = 187,
                            CouncilSeatCount = 0,
                            Name = "Skövde"
                        },
                        new
                        {
                            Id = 188,
                            CouncilSeatCount = 0,
                            Name = "Smedjebacken"
                        },
                        new
                        {
                            Id = 189,
                            CouncilSeatCount = 0,
                            Name = "Sollefteå"
                        },
                        new
                        {
                            Id = 190,
                            CouncilSeatCount = 0,
                            Name = "Sollentuna"
                        },
                        new
                        {
                            Id = 191,
                            CouncilSeatCount = 0,
                            Name = "Solna"
                        },
                        new
                        {
                            Id = 192,
                            CouncilSeatCount = 0,
                            Name = "Sorsele"
                        },
                        new
                        {
                            Id = 193,
                            CouncilSeatCount = 0,
                            Name = "Sotenäs"
                        },
                        new
                        {
                            Id = 194,
                            CouncilSeatCount = 0,
                            Name = "Staffanstorp"
                        },
                        new
                        {
                            Id = 195,
                            CouncilSeatCount = 0,
                            Name = "Stenungsund"
                        },
                        new
                        {
                            Id = 196,
                            CouncilSeatCount = 0,
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = 197,
                            CouncilSeatCount = 0,
                            Name = "Storfors"
                        },
                        new
                        {
                            Id = 198,
                            CouncilSeatCount = 0,
                            Name = "Storuman"
                        },
                        new
                        {
                            Id = 199,
                            CouncilSeatCount = 0,
                            Name = "Strängnäs"
                        },
                        new
                        {
                            Id = 200,
                            CouncilSeatCount = 0,
                            Name = "Strömstad"
                        },
                        new
                        {
                            Id = 201,
                            CouncilSeatCount = 0,
                            Name = "Strömsund"
                        },
                        new
                        {
                            Id = 202,
                            CouncilSeatCount = 0,
                            Name = "Sundbyberg"
                        },
                        new
                        {
                            Id = 203,
                            CouncilSeatCount = 0,
                            Name = "Sundsvall"
                        },
                        new
                        {
                            Id = 204,
                            CouncilSeatCount = 0,
                            Name = "Sunne"
                        },
                        new
                        {
                            Id = 205,
                            CouncilSeatCount = 0,
                            Name = "Surahammar"
                        },
                        new
                        {
                            Id = 206,
                            CouncilSeatCount = 0,
                            Name = "Svalöv"
                        },
                        new
                        {
                            Id = 207,
                            CouncilSeatCount = 0,
                            Name = "Svedala"
                        },
                        new
                        {
                            Id = 208,
                            CouncilSeatCount = 0,
                            Name = "Svenljunga"
                        },
                        new
                        {
                            Id = 209,
                            CouncilSeatCount = 0,
                            Name = "Säffle"
                        },
                        new
                        {
                            Id = 210,
                            CouncilSeatCount = 0,
                            Name = "Säter"
                        },
                        new
                        {
                            Id = 211,
                            CouncilSeatCount = 0,
                            Name = "Sävsjö"
                        },
                        new
                        {
                            Id = 212,
                            CouncilSeatCount = 0,
                            Name = "Söderhamn"
                        },
                        new
                        {
                            Id = 213,
                            CouncilSeatCount = 0,
                            Name = "Söderköping"
                        },
                        new
                        {
                            Id = 214,
                            CouncilSeatCount = 0,
                            Name = "Södertälje"
                        },
                        new
                        {
                            Id = 215,
                            CouncilSeatCount = 0,
                            Name = "Sölvesborg"
                        },
                        new
                        {
                            Id = 216,
                            CouncilSeatCount = 0,
                            Name = "Tanum"
                        },
                        new
                        {
                            Id = 217,
                            CouncilSeatCount = 0,
                            Name = "Tibro"
                        },
                        new
                        {
                            Id = 218,
                            CouncilSeatCount = 0,
                            Name = "Tidaholm"
                        },
                        new
                        {
                            Id = 219,
                            CouncilSeatCount = 0,
                            Name = "Tierp"
                        },
                        new
                        {
                            Id = 220,
                            CouncilSeatCount = 0,
                            Name = "Timrå"
                        },
                        new
                        {
                            Id = 221,
                            CouncilSeatCount = 0,
                            Name = "Tingsryd"
                        },
                        new
                        {
                            Id = 222,
                            CouncilSeatCount = 0,
                            Name = "Tjörn"
                        },
                        new
                        {
                            Id = 223,
                            CouncilSeatCount = 0,
                            Name = "Tomelilla"
                        },
                        new
                        {
                            Id = 224,
                            CouncilSeatCount = 0,
                            Name = "Torsby"
                        },
                        new
                        {
                            Id = 225,
                            CouncilSeatCount = 0,
                            Name = "Torsås"
                        },
                        new
                        {
                            Id = 226,
                            CouncilSeatCount = 0,
                            Name = "Tranemo"
                        },
                        new
                        {
                            Id = 227,
                            CouncilSeatCount = 0,
                            Name = "Tranås"
                        },
                        new
                        {
                            Id = 228,
                            CouncilSeatCount = 0,
                            Name = "Trelleborg"
                        },
                        new
                        {
                            Id = 229,
                            CouncilSeatCount = 0,
                            Name = "Trollhättan"
                        },
                        new
                        {
                            Id = 230,
                            CouncilSeatCount = 0,
                            Name = "Trosa"
                        },
                        new
                        {
                            Id = 231,
                            CouncilSeatCount = 0,
                            Name = "Tyresö"
                        },
                        new
                        {
                            Id = 232,
                            CouncilSeatCount = 0,
                            Name = "Täby"
                        },
                        new
                        {
                            Id = 233,
                            CouncilSeatCount = 0,
                            Name = "Töreboda"
                        },
                        new
                        {
                            Id = 234,
                            CouncilSeatCount = 0,
                            Name = "Uddevalla"
                        },
                        new
                        {
                            Id = 235,
                            CouncilSeatCount = 0,
                            Name = "Ulricehamn"
                        },
                        new
                        {
                            Id = 236,
                            CouncilSeatCount = 0,
                            Name = "Umeå"
                        },
                        new
                        {
                            Id = 237,
                            CouncilSeatCount = 0,
                            Name = "Upplands-Bro"
                        },
                        new
                        {
                            Id = 238,
                            CouncilSeatCount = 0,
                            Name = "Upplands Väsby"
                        },
                        new
                        {
                            Id = 239,
                            CouncilSeatCount = 0,
                            Name = "Uppsala"
                        },
                        new
                        {
                            Id = 240,
                            CouncilSeatCount = 0,
                            Name = "Uppvidinge"
                        },
                        new
                        {
                            Id = 241,
                            CouncilSeatCount = 0,
                            Name = "Vadstena"
                        },
                        new
                        {
                            Id = 242,
                            CouncilSeatCount = 0,
                            Name = "Vaggeryd"
                        },
                        new
                        {
                            Id = 243,
                            CouncilSeatCount = 0,
                            Name = "Valdemarsvik"
                        },
                        new
                        {
                            Id = 244,
                            CouncilSeatCount = 0,
                            Name = "Vallentuna"
                        },
                        new
                        {
                            Id = 245,
                            CouncilSeatCount = 0,
                            Name = "Vansbro"
                        },
                        new
                        {
                            Id = 246,
                            CouncilSeatCount = 0,
                            Name = "Vara"
                        },
                        new
                        {
                            Id = 247,
                            CouncilSeatCount = 0,
                            Name = "Varberg"
                        },
                        new
                        {
                            Id = 248,
                            CouncilSeatCount = 0,
                            Name = "Vaxholm"
                        },
                        new
                        {
                            Id = 249,
                            CouncilSeatCount = 0,
                            Name = "Vellinge"
                        },
                        new
                        {
                            Id = 250,
                            CouncilSeatCount = 0,
                            Name = "Vetlanda"
                        },
                        new
                        {
                            Id = 251,
                            CouncilSeatCount = 0,
                            Name = "Vilhelmina"
                        },
                        new
                        {
                            Id = 252,
                            CouncilSeatCount = 0,
                            Name = "Vimmerby"
                        },
                        new
                        {
                            Id = 253,
                            CouncilSeatCount = 0,
                            Name = "Vindeln"
                        },
                        new
                        {
                            Id = 254,
                            CouncilSeatCount = 0,
                            Name = "Vingåker"
                        },
                        new
                        {
                            Id = 255,
                            CouncilSeatCount = 0,
                            Name = "Vårgårda"
                        },
                        new
                        {
                            Id = 256,
                            CouncilSeatCount = 0,
                            Name = "Vänersborg"
                        },
                        new
                        {
                            Id = 257,
                            CouncilSeatCount = 0,
                            Name = "Vännäs"
                        },
                        new
                        {
                            Id = 258,
                            CouncilSeatCount = 0,
                            Name = "Värmdö"
                        },
                        new
                        {
                            Id = 259,
                            CouncilSeatCount = 0,
                            Name = "Värnamo"
                        },
                        new
                        {
                            Id = 260,
                            CouncilSeatCount = 0,
                            Name = "Västervik"
                        },
                        new
                        {
                            Id = 261,
                            CouncilSeatCount = 0,
                            Name = "Västerås"
                        },
                        new
                        {
                            Id = 262,
                            CouncilSeatCount = 0,
                            Name = "Växjö"
                        },
                        new
                        {
                            Id = 263,
                            CouncilSeatCount = 0,
                            Name = "Ydre"
                        },
                        new
                        {
                            Id = 264,
                            CouncilSeatCount = 0,
                            Name = "Ystad"
                        },
                        new
                        {
                            Id = 265,
                            CouncilSeatCount = 0,
                            Name = "Åmål"
                        },
                        new
                        {
                            Id = 266,
                            CouncilSeatCount = 0,
                            Name = "Ånge"
                        },
                        new
                        {
                            Id = 267,
                            CouncilSeatCount = 0,
                            Name = "Åre"
                        },
                        new
                        {
                            Id = 268,
                            CouncilSeatCount = 0,
                            Name = "Årjäng"
                        },
                        new
                        {
                            Id = 269,
                            CouncilSeatCount = 0,
                            Name = "Åsele"
                        },
                        new
                        {
                            Id = 270,
                            CouncilSeatCount = 0,
                            Name = "Åstorp"
                        },
                        new
                        {
                            Id = 271,
                            CouncilSeatCount = 0,
                            Name = "Åtvidaberg"
                        },
                        new
                        {
                            Id = 272,
                            CouncilSeatCount = 0,
                            Name = "Älmhult"
                        },
                        new
                        {
                            Id = 273,
                            CouncilSeatCount = 0,
                            Name = "Älvdalen"
                        },
                        new
                        {
                            Id = 274,
                            CouncilSeatCount = 0,
                            Name = "Älvkarleby"
                        },
                        new
                        {
                            Id = 275,
                            CouncilSeatCount = 0,
                            Name = "Älvsbyn"
                        },
                        new
                        {
                            Id = 276,
                            CouncilSeatCount = 0,
                            Name = "Ängelholm"
                        },
                        new
                        {
                            Id = 277,
                            CouncilSeatCount = 0,
                            Name = "Öckerö"
                        },
                        new
                        {
                            Id = 278,
                            CouncilSeatCount = 0,
                            Name = "Ödeshög"
                        },
                        new
                        {
                            Id = 279,
                            CouncilSeatCount = 0,
                            Name = "Örebro"
                        },
                        new
                        {
                            Id = 280,
                            CouncilSeatCount = 0,
                            Name = "Örkelljunga"
                        },
                        new
                        {
                            Id = 281,
                            CouncilSeatCount = 0,
                            Name = "Örnsköldsvik"
                        },
                        new
                        {
                            Id = 282,
                            CouncilSeatCount = 0,
                            Name = "Östersund"
                        },
                        new
                        {
                            Id = 283,
                            CouncilSeatCount = 0,
                            Name = "Österåker"
                        },
                        new
                        {
                            Id = 284,
                            CouncilSeatCount = 0,
                            Name = "Östhammar"
                        },
                        new
                        {
                            Id = 285,
                            CouncilSeatCount = 0,
                            Name = "Östra Göinge"
                        },
                        new
                        {
                            Id = 286,
                            CouncilSeatCount = 0,
                            Name = "Överkalix"
                        },
                        new
                        {
                            Id = 287,
                            CouncilSeatCount = 0,
                            Name = "Övertorneå"
                        });
                });

            modelBuilder.Entity("Repositories.Entities.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocal")
                        .HasColumnType("bit");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PartyName")
                        .IsUnique();

                    b.ToTable("PoliticalParties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsLocal = false,
                            PartyName = "Arbetarepartiet-Socialdemokraterna"
                        },
                        new
                        {
                            Id = 2,
                            IsLocal = false,
                            PartyName = "Moderaterna"
                        },
                        new
                        {
                            Id = 3,
                            IsLocal = false,
                            PartyName = "Sverigedemokraterna"
                        },
                        new
                        {
                            Id = 4,
                            IsLocal = false,
                            PartyName = "Centerpartiet"
                        },
                        new
                        {
                            Id = 5,
                            IsLocal = false,
                            PartyName = "Vänsterpartiet"
                        },
                        new
                        {
                            Id = 6,
                            IsLocal = false,
                            PartyName = "Kristdemokraterna"
                        },
                        new
                        {
                            Id = 7,
                            IsLocal = false,
                            PartyName = "Liberalerna"
                        },
                        new
                        {
                            Id = 8,
                            IsLocal = false,
                            PartyName = "Miljöpartiet de gröna"
                        });
                });

            modelBuilder.Entity("Repositories.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("FailedLogIns")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MunicipalityPoliticalParty", b =>
                {
                    b.HasOne("Repositories.Entities.Municipality", null)
                        .WithMany()
                        .HasForeignKey("MunicipalitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", null)
                        .WithMany()
                        .HasForeignKey("PoliticalPartiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocation", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("CouncilSeatAllocations")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.ElectionResult", "ElectionResult")
                        .WithMany("CouncilSeatAllocations")
                        .HasForeignKey("ElectionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("CouncilSeatAllocations")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("ElectionResult");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Repositories.Entities.CouncilSeatAllocationScenario", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.User", "User")
                        .WithMany("CouncilSeatAllocationScenarios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Municipality");

                    b.Navigation("PoliticalParty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionResult", b =>
                {
                    b.HasOne("Repositories.Entities.Election", "Election")
                        .WithMany("ElectionResults")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Municipality", "Municipality")
                        .WithMany("ElectionResults")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("ElectionResults")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Municipality");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Repositories.Entities.Election", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");

                    b.Navigation("CouncilSeatAllocations");

                    b.Navigation("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.ElectionResult", b =>
                {
                    b.Navigation("CouncilSeatAllocations");
                });

            modelBuilder.Entity("Repositories.Entities.Municipality", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");

                    b.Navigation("CouncilSeatAllocations");

                    b.Navigation("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.PoliticalParty", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");

                    b.Navigation("ElectionResults");
                });

            modelBuilder.Entity("Repositories.Entities.User", b =>
                {
                    b.Navigation("CouncilSeatAllocationScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
